# Generated by Django 5.2.17 on 2026-08-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_device_and_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
